### ISSUE TITLE
Inject agent custom

### ISSUE THREAD

**Issue by tpinguer** [lucassm02/nodejs-template#20]
#### Overview: 📃

Various configurations are made in the template to abstract and simplify development and assist in writing the code to make it more readable and standardized.

#### Current scenario: 📄

Today I need to inject a customized agent into the request and the one implemented today doesn't work for me

#### Acceptance criteria: 👍🏼

- [ ] Being able to inject a customized HTTP/HTTPS agent.

#### Comments: 📝

It would be interesting to have a way of loading the agent in each request or replacing the default one.

**Comment by lucassm02** [comment]
@tpinguer thanks for the contribution, closed by #24.
